### ISSUE TITLE
Workspace Closed Error (Version 2.7.1)

### ISSUE THREAD

**Issue by rubensgomes** [revelc/formatter-m2e-configurator#3]
I am getting "Workspace Closed Error" with the latest version (2.7.1) of this plugin.  Please, see details below:

[INFO] --- formatter-maven-plugin:2.7.1:format (format-code) @ starterkit-ms ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.                         nodeCount=29, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=2                         4, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=1, ConflictResolver.conflictItemCount=2                         9, DefaultDependencyCollector.collectTime=111, DefaultDependencyCollector.transformTime=1}
[DEBUG] net.revelc.code.formatter:formatter-maven-plugin:jar:2.7.1:
[DEBUG]    com.fasterxml.jackson.core:jackson-core:jar:2.9.2:compile
[DEBUG]    com.fasterxml.jackson.core:jackson-databind:jar:2.9.2:compile
[DEBUG]       com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[DEBUG]    com.google.guava:guava:jar:23.3-jre:compile
[DEBUG]       com.google.code.findbugs:jsr305:jar:1.3.9:compile
[DEBUG]       com.google.errorprone:error_prone_annotations:jar:2.0.18:compile
[DEBUG]       com.google.j2objc:j2objc-annotations:jar:1.1:compile
[DEBUG]       org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
[DEBUG]    net.revelc.code.formatter:jsdt-core:jar:2.6.0:compile
[DEBUG]    net.sourceforge.cssparser:cssparser:jar:0.9.23:compile
[DEBUG]    org.apache.commons:commons-digester3:jar:3.2:compile
[DEBUG]       cglib:cglib:jar:2.2.2:compile
[DEBUG]          asm:asm:jar:3.3.1:compile
[DEBUG]       commons-beanutils:commons-beanutils:jar:1.8.3:compile
[DEBUG]       commons-logging:commons-logging:jar:1.1.1:compile
[DEBUG]    org.codehaus.plexus:plexus-resources:jar:1.1.0:compile
[DEBUG]       org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile
[DEBUG]          junit:junit:jar:3.8.1:compile
[DEBUG]          classworlds:classworlds:jar:1.1-alpha-2:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:3.1.0:compile
[DEBUG]    org.eclipse.tycho:org.eclipse.jdt.core:jar:3.13.50.v20171007-0855:compile
[DEBUG]    org.jsoup:jsoup:jar:1.10.3:compile
[DEBUG]    org.w3c.css:sac:jar:1.3:compile
[DEBUG] Created new class realm plugin>net.revelc.code.formatter:formatter-maven-plugin:2.7.1
[DEBUG] Importing foreign packages into class realm plugin>net.revelc.code.formatter:formatter-maven-plugin:2.                         7.1
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>net.revelc.code.formatter:formatter-maven-plugin:2.7.1
[DEBUG]   Included: net.revelc.code.formatter:formatter-maven-plugin:jar:2.7.1
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-core:jar:2.9.2
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-databind:jar:2.9.2
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0
[DEBUG]   Included: com.google.guava:guava:jar:23.3-jre
[DEBUG]   Included: com.google.code.findbugs:jsr305:jar:1.3.9
[DEBUG]   Included: com.google.errorprone:error_prone_annotations:jar:2.0.18
[DEBUG]   Included: com.google.j2objc:j2objc-annotations:jar:1.1
[DEBUG]   Included: org.codehaus.mojo:animal-sniffer-annotations:jar:1.14
[DEBUG]   Included: net.revelc.code.formatter:jsdt-core:jar:2.6.0
[DEBUG]   Included: net.sourceforge.cssparser:cssparser:jar:0.9.23
[DEBUG]   Included: org.apache.commons:commons-digester3:jar:3.2
[DEBUG]   Included: cglib:cglib:jar:2.2.2
[DEBUG]   Included: asm:asm:jar:3.3.1
[DEBUG]   Included: commons-beanutils:commons-beanutils:jar:1.8.3
[DEBUG]   Included: commons-logging:commons-logging:jar:1.1.1
[DEBUG]   Included: org.codehaus.plexus:plexus-resources:jar:1.1.0
[DEBUG]   Included: junit:junit:jar:3.8.1
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.1.0
[DEBUG]   Included: org.eclipse.tycho:org.eclipse.jdt.core:jar:3.13.50.v20171007-0855
[DEBUG]   Included: org.jsoup:jsoup:jar:1.10.3
[DEBUG]   Included: org.w3c.css:sac:jar:1.3
[DEBUG] Configuring mojo net.revelc.code.formatter:formatter-maven-plugin:2.7.1:format from plugin realm Class                         Realm[plugin>net.revelc.code.formatter:formatter-maven-plugin:2.7.1, parent: sun.misc.Launcher$AppClassLoader@                         5c647e05]
[DEBUG] Configuring mojo 'net.revelc.code.formatter:formatter-maven-plugin:2.7.1:format' with basic configurat                         or -->
[DEBUG]   (f) basedir = C:\git\tfsgit\StarterKitMS
[DEBUG]   (f) compilerCompliance = 1.8
[DEBUG]   (f) compilerSource = 1.8
[DEBUG]   (f) compilerTargetPlatform = 1.8
[DEBUG]   (f) configCssFile = formatter-maven-plugin/ph-css/css.properties
[DEBUG]   (f) configFile = C:\git\tfsgit\StarterKitMS/misc/eclipse-java-formatter-config.xml
[DEBUG]   (f) configHtmlFile = formatter-maven-plugin/jsoup/html.properties
[DEBUG]   (f) configJsFile = formatter-maven-plugin/eclipse/javascript.xml
[DEBUG]   (f) configJsonFile = formatter-maven-plugin/jackson/json.properties
[DEBUG]   (f) configXmlFile = formatter-maven-plugin/jsoup/xml.properties
[DEBUG]   (f) encoding = UTF-8
[DEBUG]   (f) includes = []
[DEBUG]   (f) lineEnding = LF
[DEBUG]   (f) skipCssFormatting = true
[DEBUG]   (f) skipFormatting = false
[DEBUG]   (f) skipHtmlFormatting = true
[DEBUG]   (f) skipJavaFormatting = false
[DEBUG]   (f) skipJsFormatting = true
[DEBUG]   (f) skipJsonFormatting = true
[DEBUG]   (f) skipXmlFormatting = true
[DEBUG]   (f) sourceDirectory = C:\git\tfsgit\StarterKitMS\src\main\java
[DEBUG]   (f) targetDirectory = C:\git\tfsgit\StarterKitMS\target
[DEBUG]   (f) testSourceDirectory = C:\git\tfsgit\StarterKitMS\src\test\java
[DEBUG]   (f) useEclipseDefaults = false
[DEBUG] -- end configuration --
[INFO] Using 'UTF-8' encoding to format source files.
[INFO] Number of files to be formatted: 46
[DEBUG] Using search path at: C:\git\tfsgit\StarterKitMS
[DEBUG] The resource 'C:\git\tfsgit\StarterKitMS/misc/eclipse-java-formatter-config.xml' was not found with re                         sourceLoader org.codehaus.plexus.resource.loader.ThreadContextClasspathResourceLoader.
[DEBUG] The resource 'C:\git\tfsgit\StarterKitMS/misc/eclipse-java-formatter-config.xml' was not found with re                         sourceLoader org.codehaus.plexus.resource.loader.JarResourceLoader.
[DEBUG] The resource 'C:\git\tfsgit\StarterKitMS/misc/eclipse-java-formatter-config.xml' was found as C:\git\t                         fsgit\StarterKitMS\misc\eclipse-java-formatter-config.xml.
[DEBUG] Using search path at: C:\git\tfsgit\StarterKitMS
[DEBUG] The resource 'formatter-maven-plugin/eclipse/javascript.xml' was found as jar:file:/C:/Users/816461/.m                         2/repository/net/revelc/code/formatter/formatter-maven-plugin/2.7.1/formatter-maven-plugin-2.7.1.jar!/formatte                         r-maven-plugin/eclipse/javascript.xml.
[DEBUG] Using search path at: C:\git\tfsgit\StarterKitMS
[DEBUG] The resource 'formatter-maven-plugin/jsoup/html.properties' was found as jar:file:/C:/Users/816461/.m2                         /repository/net/revelc/code/formatter/formatter-maven-plugin/2.7.1/formatter-maven-plugin-2.7.1.jar!/formatter                         -maven-plugin/jsoup/html.properties.
[DEBUG] Using search path at: C:\git\tfsgit\StarterKitMS
[DEBUG] The resource 'formatter-maven-plugin/jsoup/xml.properties' was found as jar:file:/C:/Users/816461/.m2/                         repository/net/revelc/code/formatter/formatter-maven-plugin/2.7.1/formatter-maven-plugin-2.7.1.jar!/formatter-                         maven-plugin/jsoup/xml.properties.
[DEBUG] Using search path at: C:\git\tfsgit\StarterKitMS
[DEBUG] The resource 'formatter-maven-plugin/jackson/json.properties' was found as jar:file:/C:/Users/816461/.                         m2/repository/net/revelc/code/formatter/formatter-maven-plugin/2.7.1/formatter-maven-plugin-2.7.1.jar!/formatt                         er-maven-plugin/jackson/json.properties.
[DEBUG] Using search path at: C:\git\tfsgit\StarterKitMS
[DEBUG] The resource 'formatter-maven-plugin/ph-css/css.properties' was found as jar:file:/C:/Users/816461/.m2                         /repository/net/revelc/code/formatter/formatter-maven-plugin/2.7.1/formatter-maven-plugin-2.7.1.jar!/formatter                         -maven-plugin/ph-css/css.properties.
[DEBUG] Processing file: C:\git\tfsgit\StarterKitMS\src\main\java\com\aa\etds\starterkit\Application.java
[DEBUG] Processing file: C:\git\tfsgit\StarterKitMS\src\main\java\com\aa\etds\starterkit\Application.java with                          line ending: LF
[DEBUG] Nothing formatted. Try to fix line endings.
[DEBUG] Equal code. Not writing result to file.
.... ....
.... ....

[DEBUG] Processing file: C:\git\tfsgit\StarterKitMS\src\main\java\com\aa\etds\starterkit\common\dto\DateTimest                         amp.java with line ending: LF
[DEBUG] Nothing formatted. Try to fix line endings.
[DEBUG] Equal code. Not writing result to file.
[DEBUG] Processing file: C:\git\tfsgit\StarterKitMS\src\main\java\com\aa\etds\starterkit\common\dto\ErrorInfo.                         java
[DEBUG] Processing file: C:\git\tfsgit\StarterKitMS\src\main\java\com\aa\etds\starterkit\common\dto\ErrorInfo.                         java with line ending: LF
[DEBUG] Nothing formatted. Try to fix line endings.
[DEBUG] Equal code. Not writing result to file.
[DEBUG] Processing file: C:\git\tfsgit\StarterKitMS\src\main\java\com\aa\etds\starterkit\common\dto\GitInfo.ja                         va
[DEBUG] Processing file: C:\git\tfsgit\StarterKitMS\src\main\java\com\aa\etds\starterkit\common\dto\GitInfo.ja                         va with line ending: LF
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.867 s
[INFO] Finished at: 2017-12-03T08:04:13-06:00
[INFO] Final Memory: 32M/302M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.7.1:format (format-code) on                          project starterkit-ms: Execution format-code of goal net.revelc.code.formatter:formatter-maven-plugin:2.7.1:fo                         rmat failed: Workspace is closed. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.revelc.code.formatter:forma                         tter-maven-plugin:2.7.1:format (format-code) on project starterkit-ms: Execution format-code of goal net.revel                         c.code.formatter:formatter-maven-plugin:2.7.1:format failed: Workspace is closed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java                         :117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java                         :81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThread                         edBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution format-code of goal net.revelc.code.for                         matter:formatter-maven-plugin:2.7.1:format failed: Workspace is closed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.lang.IllegalStateException: Workspace is closed.
        at org.eclipse.core.resources.ResourcesPlugin.getWorkspace(ResourcesPlugin.java:412)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.createParser(DefaultCodeFormatter.java:332)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.parseSourceCode(DefaultCodeFormatter.java:3                         17)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareFormattedCode(DefaultCodeFormatter.j                         ava:213)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareFormattedCode(DefaultCodeFormatter.j                         ava:206)
        at org.eclipse.jdt.internal.formatter.CommentsPreparator.formatCode(CommentsPreparator.java:1063)
        at org.eclipse.jdt.internal.formatter.CommentsPreparator.handleFormatCodeTag(CommentsPreparator.java:8                         01)
        at org.eclipse.jdt.internal.formatter.CommentsPreparator.handleHtml(CommentsPreparator.java:665)
        at org.eclipse.jdt.internal.formatter.CommentsPreparator.endVisit(CommentsPreparator.java:621)
        at org.eclipse.jdt.core.dom.TagElement.accept0(TagElement.java:282)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2867)
        at org.eclipse.jdt.core.dom.Javadoc.accept0(Javadoc.java:205)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareComments(DefaultCodeFormatter.java:3                         99)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareFormattedCode(DefaultCodeFormatter.j                         ava:222)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(DefaultCodeFormatter.java:177)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(DefaultCodeFormatter.java:160)
        at net.revelc.code.formatter.java.JavaFormatter.doFormat(JavaFormatter.java:46)
        at net.revelc.code.formatter.AbstractCacheableFormatter.formatFile(AbstractCacheableFormatter.java:47)
        at net.revelc.code.formatter.FormatterMojo.doFormatFile(FormatterMojo.java:511)
        at net.revelc.code.formatter.FormatterMojo.formatFile(FormatterMojo.java:466)
        at net.revelc.code.formatter.FormatterMojo.execute(FormatterMojo.java:344)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by ctubbsii** [comment]
@rubensgomes , it seems like you're seeing the error identified on revelc/formatter-maven-plugin#260

**Comment by ctubbsii** [comment]
Closing this, as it does not pertain to the m2e-configurator, but to the formatter-maven-plugin.
